# Generated by Django 4.2.6 on 2023-11-06 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210709_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
    ]
